const sellerRoutes = {
    sellerSignup: '/seller/verifyEmail',
    sellerVerifyOtp: '/seller/verifyOtp',
    sellerResendOtp: '/seller/resendOtp',
    sellerLogin: '/seller/login',
    sellerProfile: '/seller/profile',
    sellerEditProfile: '/seller/editProfile',
    sellerLogout: '/seller/logout',
    sellerCreateProperty: '/seller/createProperty',
    sellerEditProperty: '/seller/editProperty',
    sellerList: '/seller/sellerList',
    sellerGetUser: '/seller/getUser',
    sellerGetConversations: '/chat/getConversation',
    sellerFindUserById: '/chat/findUserById',
    sellerGetBooking: '/book/getBookingBySellerId',
    dashboard: '/seller/dashboard',
    getMonthlySales: '/seller/getMonthlySales',
    getMonthlyRevenue: '/seller/getMonthlyRevenue',
    addReply: '/seller/addReply',
    findPropertyById: '/seller/findPropertyById',
    proceedForSubscription: '/book/proceedForSubscription',
    cancelSubscription: '/book/cancelSubscription',
    getNotification: '/seller/getNotification',
}

export default sellerRoutes